### ISSUE TITLE
Is there a way to go above zoom level 5?

### ISSUE THREAD

**Issue by Sireini** [bramus/photoshop-google-maps-tile-cutter#11]
I want to create a google map where it is possible to zoom in very close to the map, but it is not going further than 5?

**Comment by bramus** [comment]
tl;dr — In order to have more zoom levels generated, use a bigger image as the source for the tilecutter.

Tiles have a (default) size of `256px` by `256px`. If you feed the tilecutter an image of `512px` by `512px` you'll have 2 zoom levels cut out. Feed it a `1024px` by `1024px` image, you'll have 3 zoom levels cut out. Feed it a `2048px` by `2048px` ... you get the idea ;-)

The tilecutter will stop at the highest zoomlevel it can cut out, without enlarging the source image.
